##-----------------------------------------##
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
##-----------------------------------------##
/output/filename ./sim_output.root
/stack/killsecondaries 0 # kill all secondaries
/run/initialize

/vis/open OGL

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi -90. -89.9
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100
/vis/scene/add/trajectories rich smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByCharge-0/default/setDrawAuxPts true
/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByCharge-0/default/setTimeSliceInterval 0.001 ns

#- Axes, scale, etc.
/vis/scene/add/axes 0 0 0 0.5 m # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/date    # Date stamp

/vis/scene/list
/vis/drawTree
##-----------------------------------------##
/run/beamOn 10
##-----------------------------------------##
